name: electron-windows-nsis-build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install --prefer-offline --no-frozen-lockfile

      - name: Build Electron App
        run: pnpm run build

      - name: Check NSIS installation
        run: |
          $nsisPath = "C:\Users\runneradmin\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin"
          if (Test-Path "$nsisPath\makensis.exe") {
            Write-Host "NSIS found at $nsisPath"
            & "$nsisPath\makensis.exe" /VERSION
          } else {
            Write-Host "NSIS not found at $nsisPath"
            exit 1
          }
        shell: powershell

      - name: Build and publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ELECTRON_BUILDER_NSIS_DIR: C:\Users\runneradmin\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin
        run: |
          pnpx electron-builder --win --publish always --config.asar=false --config.asarUnpack=** --debug
        shell: powershell

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./release/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
