name: electron-windows-nsis-build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        shell: powershell
        run: |
          Start-Process powershell -Verb RunAs -ArgumentList "-Command pnpm install --prefer-offline --no-frozen-lockfile" -Wait

      - name: Build Electron App
        shell: powershell
        run: |
          Start-Process powershell -Verb RunAs -ArgumentList "-Command pnpm run build" -Wait

      - name: Before check nsis dir
        shell: powershell
        run: |
          Start-Process powershell -Verb RunAs -ArgumentList "-Command `"
          # 1. runneradmin 사용자 디렉토리 확인
          dir C:\Users\runneradmin
          # 2. AppData 디렉토리 확인
          dir C:\Users\runneradmin\AppData
          # 3. AppData\Local 디렉토리 확인
          dir C:\Users\runneradmin\AppData\Local
          # 4. electron-builder 디렉토리 확인
          dir C:\Users\runneradmin\AppData\Local\electron-builder
          # 5. Cache 디렉토리 확인
          dir C:\Users\runneradmin\AppData\Local\electron-builder\Cache
          # 6. nsis 디렉토리 확인
          dir C:\Users\runneradmin\AppData\Local\electron-builder\Cache\nsis
          # 7. nsis-3.0.4.1 디렉토리 확인
          dir C:\Users\runneradmin\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1
          # 8. Bin 디렉토리 확인
          dir C:\Users\runneradmin\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin
          # 9. makensis.exe 파일 확인
          if (Test-Path C:\Users\runneradmin\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe) {
              Write-Host 'makensis.exe exists'
          } else {
              Write-Host 'makensis.exe does not exist'
          }
          # 10. makensis.exe 파일 정보 확인 (파일이 존재하는 경우)
          if (Test-Path C:\Users\runneradmin\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe) {
              Get-ItemProperty C:\Users\runneradmin\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe
          }
          `"" -Wait
        continue-on-error: true

      - name: build
        shell: powershell
        run: |
          Start-Process powershell -Verb RunAs -ArgumentList "-Command pnpx electron-builder --win --publish always" -Wait
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: After check nsis dir
        shell: powershell
        run: |
          Start-Process powershell -Verb RunAs -ArgumentList "-Command `"
          # 1. runneradmin 사용자 디렉토리 확인
          dir C:\Users\runneradmin
          # 2. AppData 디렉토리 확인
          dir C:\Users\runneradmin\AppData
          # 3. AppData\Local 디렉토리 확인
          dir C:\Users\runneradmin\AppData\Local
          # 4. electron-builder 디렉토리 확인
          dir C:\Users\runneradmin\AppData\Local\electron-builder
          # 5. Cache 디렉토리 확인
          dir C:\Users\runneradmin\AppData\Local\electron-builder\Cache
          # 6. nsis 디렉토리 확인
          dir C:\Users\runneradmin\AppData\Local\electron-builder\Cache\nsis
          # 7. nsis-3.0.4.1 디렉토리 확인
          dir C:\Users\runneradmin\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1
          # 8. Bin 디렉토리 확인
          dir C:\Users\runneradmin\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin
          # 9. makensis.exe 파일 확인
          if (Test-Path C:\Users\runneradmin\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe) {
              Write-Host 'makensis.exe exists'
          } else {
              Write-Host 'makensis.exe does not exist'
          }
          # 10. makensis.exe 파일 정보 확인 (파일이 존재하는 경우)
          if (Test-Path C:\Users\runneradmin\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe) {
              Get-ItemProperty C:\Users\runneradmin\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe
          }
          `"" -Wait
        continue-on-error: true

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./release/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
